# Site settings
title: "Recinto do Copista"
author: "Abu-Becre Alcidique de França Bandeira"
description: "Est'é um site pessoal onde escrevo que me der e vier; qualquer tópico será falado sobre aqui."
keywords: "Software Engineering, Mathematics, Philosophy, Scala, Epistemology, Existentialism, Programming, Machine-Learning, Artificial Intelligence, Statistics, Probability, Puzzles"
biography: "Sou um doido pedante e autista que tem a necessidade de se expressar."
colophon: "© MMXXI - Feito por Abu-Becre Alcidique de França Bandeira. <br>Conteúdo disponível em <a href='http://creativecommons.org/licenses/by-nc-sa/4.0/'>Creative Commons (BY-NC-SA)</a>"

baseurl: "/"
url: "https://copista-velho.github.io/"

twitter_username: CopistaVelho

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
